# NUMPY

In [2]:
import numpy as np

## generate array of zeros

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## generate array of ones

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## generate full array with arbitrary number (size, number)

In [9]:
np.full(10,14)

array([14, 14, 14, 14, 14, 14, 14, 14, 14, 14])

## convert list into array

In [14]:
np.array([1,5,7,2,0])

array([1, 5, 7, 2, 0])

## creates a range of numbers (start, end(exclusive))

In [17]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## create evenly space array (start, end, space)

In [ ]:
np.linspace(0,100,11)

## Multi-Dimensional Arrays

### Define arrays

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
n = np.array([[0,0,0], [0,0,0], [0,0,0]])

### Update Arrays

In [11]:
n[0,0] = 14

In [14]:
n[1] = 5

In [17]:
n[:, 2] = 3

In [18]:
n

array([[14,  0,  3],
       [ 5,  5,  3],
       [ 0,  0,  3]])

### Random generated array (row,col) -> 0-1

In [61]:
np.random.seed(2)

In [60]:
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [64]:
np.random.randn(5,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [92]:
np.random.randint(low=6,high=(14),size=(5,2)) # high exclusive

array([[12,  6],
       [11, 12],
       [ 9,  7],
       [11,  7],
       [11,  7]])

## Operationon Arrays

### Element-wise operations

In [4]:
a = np.array([3,1,7,5])

In [ ]:
b = a + 3 # add, substract, multiply or divide

In [12]:
b = 3 + (a-4) # operation chaining

In [13]:
b

array([2, 0, 6, 4])